version: '3.5'
services:
    airflow-metastore:
        image: postgres:12
        container_name: airflow-metastore
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}         

    web:
        image: apache/airflow:1.10.10-python3.5
        depends_on: 
           - airflow-metastore
        environment:
            - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - AIRFLOW__CORE__EXECUTOR=${EXECUTOR} 
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
        ports:
            - 8080:8080
        entrypoint: /entrypoint.sh
        command: 'webserver'

    airflow-scheduler:
        image: apache/airflow:1.10.10-python3.5
        depends_on: 
            - web
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
        environment:
            - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - AIRFLOW__CORE__EXECUTOR=${EXECUTOR}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        entrypoint: /entrypoint.sh
        command: 'scheduler'
