version: '3.5'
services:
    airflow-metastore:
        image: mysql:5.7
        container_name: airflow-metastore
        environment:
            - MYQSL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DB=${MYSQL_DB}
            - MYSQL_HOST=${MYSQL_HOST}

    web:
        image: apache/airflow:1.10.10-python3.5
        depends_on: 
           - airflow-metastore
        environment:
            - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - AIRFLOW__CORE__EXECUTOR=${EXECUTOR} 
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql://${MYSQL_ROOT_USER}:${MYSQL-ROOT_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
        ports:
            - 8080:8080
        entrypoint: /entrypoint.sh
        command: 'webserver'

    airflow-scheduler:
        image: apache/airflow:1.10.10-python3.5
        depends_on: 
            - web
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
        environment:
            - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - AIRFLOW__CORE__EXECUTOR=${EXECUTOR}
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        entrypoint: /entrypoint.sh
        command: 'scheduler'
